# SPDX-License-Identifier: GPL-3.0-or-later
# Read after PS5_Vulkan's tooling/radv/ps5-cross.ini (tools/pyrowave/meson-ccache.sh):
# the same SDK compilers, called through ccache. `sdk` comes from the constants
# file tools/build-radv.sh writes.

[binaries]
c = ['ccache', sdk / 'bin/prospero-clang']
cpp = ['ccache', sdk / 'bin/prospero-clang++']
