#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
import pathlib, subprocess, struct, tempfile
root=pathlib.Path(__file__).resolve().parents[2]
lines=['// Generated by tools/compile-shaders.py; SPDX-License-Identifier: MIT','#pragma once','#include <cstdint>']
with tempfile.TemporaryDirectory() as temp:
    for stage in ['vert','frag']:
        target=pathlib.Path(temp)/('yuv.'+stage+'.spv')
        subprocess.run(['glslangValidator','-V','--target-env','vulkan1.3','-o',str(target),str(root/'src/pyrowave/video'/('yuv.'+stage))],check=True)
        data=target.read_bytes(); words=struct.unpack('<'+'I'*(len(data)//4),data)
        lines.append('inline constexpr uint32_t yuv_'+stage+'[] = {'+','.join(hex(w) for w in words)+'};')
(root/'src/pyrowave/video/yuv_spirv.hpp').write_text('\n'.join(lines)+'\n')
